language: r

r:
  - oldrel
  - release
  - devel
  - bioc-devel

r_packages:
  - testthat

cache:
  - packages

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change
